### PR TITLE
Filename Set from Config

### PR DESCRIPTION
**Pull request by pjlamb12**
feat(rss): add filename to config

Allow the name of the file that the feeds will use to be set using config

### CODE REVIEW

**Comment by pjlamb12** [comment]
Any updates on when this can be merged and deployed?

**Comment by pjlamb12** [comment]
@marcjulian just wondering if you might be able to merge and deploy this in the next day or so?

**Comment by marcjulian** [comment]
@pjlamb12 sorry. Yes I will get back on it and release it soon!

**Comment by pjlamb12** [comment]
Thanks so much!

**Comment by marcjulian** [comment]
💯

**Comment by marcjulian** [comment]
@pjlamb12 [@notiz/scully-plugin-rss@1.1.0](https://github.com/notiz-dev/scully-plugins/releases/tag/%40notiz%2Fscully-plugin-rss%401.1.0) has been released thanks again!

**Comment by pjlamb12** [comment]
Thank you!

**Pull request merged**
