### PR TITLE
calculate image sizes

### PR DESCRIPTION
**Pull request by garygrossgarten**
@marcjulian I updated the lazy plugin to precalculate and set image dimensions to stop layout shiftings when scrolling/ loading the images happens

### CODE REVIEW

**Comment by garygrossgarten** [comment]
@marcjulian Please release a beta version for this so that we can test it in notiz before merging

**Comment by marcjulian** [comment]
0.3.0-beta.0 is available

**Comment by garygrossgarten** [comment]
My changes don't work yet...

**Comment by garygrossgarten** [comment]
@marcjulian It's working now but the scully command doesn't finish. Any idea?

**Pull request merged**
